### ISSUE TITLE
omg cherax best menu, your loader is the best i have seen

### ISSUE THREAD

**Issue by brunph** [theHorizonGTA/AHUFDWS#1]
https://github.com/theHorizonGTA/AHUFDWS/commit/3598ec977f20d073172bdfba1f9258ce05bdcd86
https://github.com/theHorizonGTA/AHUFDWS/commit/3598ec977f20d073172bdfba1f9258ce05bdcd86
https://github.com/theHorizonGTA/AHUFDWS/commit/3598ec977f20d073172bdfba1f9258ce05bdcd86

CHERAX NUMBER 1 P2C OUT THERE, SECURITY ON TOP!!!!!!!!!!!!!

**Comment by Unknxwn007** [comment]
omg brunph my baby where have you been

**Comment by Unknxwn007** [comment]
oh fixed!
